version: '3'

services:
  app:
    image: dummy-app:1.0.0
    build:
      context: ../dummy-app
      dockerfile: Dockerfile
    network_mode: host

  filebeat:
    hostname: filebeat
    network_mode: host
    image: filebeat:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # not dockerized service
      # - "/home/ruma/log/uwsgi/uwsgi.log:/usr/share/log/uwsgi.log:ro"
      - "/var/lib/docker/containers:/usr/share/filebeat/logs" # access all docker logs (read only)
      - "/var/run/docker.sock:/var/run/docker.sock" # additional info about containers
    environment:
      - host=172.20.20.207