version: '3'

services:
  app:
    image: filebeat-es_k/dummy-app:1.0.0
    build:
      context: dummy-app
      dockerfile: Dockerfile
    network_mode: host

  filebeat:
    hostname: filebeat
    network_mode: host
    image: filebeat-es_k/filebeat:1.0.0
    build:
      context: filebeat
      dockerfile: Dockerfile
    volumes:
      # not dockerized service
      # - "/home/ruma/log/uwsgi/uwsgi.log:/usr/share/log/uwsgi.log:ro"
      - "/var/lib/docker/containers:/usr/share/filebeat/logs:ro" # access all docker logs (read only)
      - "/var/run/docker.sock:/var/run/docker.sock" # additional info about containers
    # environment:
    #   - host=localhost

  kibana:
    hostname: kibana
    image: filebeat-es_k/kibana:1.0.0
    build: 
      context: kibana
      dockerfile: Dockerfile
    environment:
      - "LOGGING_QUIET=true"
      - port=5601
    network_mode: host
    volumes: 
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"

  elasticsearch:
    hostname: elasticsearch
    image: filebeat-es_k/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: host
