version: '3'

services:
  kibana:
    image: kibana:6.5.2
    environment:
      - "LOGGING_QUIET=true"
      - port=5601
    links:
      - elasticsearch
    network_mode: host

  elasticsearch:
    hostname: elasticsearch
    image: docker-logs-elk/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: host
