version: '3'

services:
  kibana:
    hostname: kibana
    image: kibana:1.0.0
    build: 
      context: ../kibana
      dockerfile: Dockerfile
    environment:
      - "LOGGING_QUIET=true"
      - port=5601
    network_mode: host
    volumes: 
      - "../kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"

  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: host
